<font size="2">
<p><strong>Seções<br></strong></p>
<p><a href="cartaz.php">EM CARTAZ</a></p>
<p><a href="destaques.php">DESTAQUES</a></p>
<p><a href="breve.php">EM BREVE</a></p>
<p><a href="trilha.php">TRILHA SONORA</a></p>
<p><a href="ranking.php">RANKING</a></p>
<p><a href="trailer.php">TRAILER</a></p>
<p><a href="bilheteria.php">BILHETERIA</a></p>
<p><a href="programacao.php">PROGRAMAÇÃO</a></p>
<p><a href="fotos.php">FOTOS</a></p>
<p><a href="links.php">LINKS</a></p>
<p><a href="arquivo.php">ARQUIVO</a></p>
<p><a href="opiniao.php">OPINIÃO</a></p>
</font>
